# Generated by Django 6.0.2 on 2026-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='end',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='start',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
